name: Test_Change
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: "json"
          fileOutput: "json"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run changes files through test script
        run: |
          npm i
          npm install -g ts-node
          for i in $(echo ${{ steps.file_changes.outputs.files_modified}} | tr  -d '[]' | tr "," "\n")
          do 
            { 
              ls home/runner/work
              ls home/runner/work/emissions-adapters
              ls home/runner/work/emissions-adapters/emissions-adapters
              ts-node ${{ github.workspace }}/utils/test.ts ${{ github.workspace }}/${i} true
              ts-node ${{ github.workspace }}/utils/comment.ts /home/runner/work/emissions-adapters/emissions-adapters/result.txt "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}" ${i}
            } || { 
              echo -n $i
              echo ' doesnt run'
            }
          done
          # for i in $(echo ${{ steps.file_changes.outputs.files_added}} | tr  -d '[]' | tr "," "\n")
          # do 
          #   { 
          #     ts-node ${{ github.workspace }}/utils/test.ts ${{ github.workspace }}/${i} true
          #     ts-node ${{ github.workspace }}/utils/comment.ts /home/runner/work/emissions-adapters/emissions-adapters/result.txt "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}" ${i}
          #   } || { 
          #     echo -n $i
          #     echo ' doesnt run'
          #   }
          # done
