name: Test_Change
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: "json"
          fileOutput: "json"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run changes files through test script
        run: |
          npm i
          npm install -g ts-node
          for i in $(echo ${{ steps.file_changes.outputs.files_modified}} | tr  -d '[]' | tr "," "\n")
          do 
            { 
              ts-node ${{ github.workspace }}/utils/test.ts ${{ github.workspace }}/${i} > output.txt 
              node ${{ github.workspace }}/.github/workflows/comment.js /home/runner/work/emissions-adapters/emissions-adapters/output.txt "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}" ${i}
            } || { 
              echo -n $i
              echo ' doesnt run'
            }
          done
          for i in $(echo ${{ steps.file_changes.outputs.files_added}} | tr  -d '[]' | tr "," "\n")
          do 
            { 
              ts-node ${{ github.workspace }}/utils/test.ts ${{ github.workspace }}/${i} > output.txt 
              node ${{ github.workspace }}/.github/workflows/comment.js /home/runner/work/emissions-adapters/emissions-adapters/output.txt "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}" ${i}
            } || { 
              echo -n $i
              echo ' doesnt run'
            }
          done
