name: Test_Change
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: "json"
          fileOutput: "json"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run changes files through test script
        run: |
          RUN_FILES=$(
            MODIFIED=${{ steps.file_changes.outputs.files_modified}} \
            ADDED=${{ steps.file_changes.outputs.files_added}}
          )

          if [ "$RUN_FILES" = "[]" ]; then
            echo "No files were modified"
            exit 0
          fi

          # npm ci --omit=dev
          npm ci
          # npm update @defillama/sdk

          echo 'doing'
          for i in $(echo $RUN_FILES | tr  -d '"[]' | tr "," "\n")
          do 
            { 
              node ${{ github.workspace }}/utils/test.ts ${{ github.workspace }}/${i}
              node ${{ github.workspace }}/.github/workflows/comment.js /home/runner/work/emissions-adapters/emissions-adapters/utils/result.png "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}" ${i}
            } || { 
              echo -n $i
              echo ' doesnt run'
            }
          done
